#!/usr/bin/env python
# Phase1 一键运行：LNB-MDT 构建 -> PEG 生长 -> 去水去离子 -> 生成 pipe.sh 并运行

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


def _load_yaml_min(path: Path) -> dict:
    # 优先用 PyYAML
    try:
        import yaml  # type: ignore

        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:
        # 简易解析（只支持本 demo 用法）
        data: dict = {}
        cur = data
        stack: list[tuple[int, dict]] = [(-1, data)]
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.rstrip()
            if not line or line.strip().startswith("#"):
                continue
            indent = len(line) - len(line.lstrip(" "))
            keyval = line.strip()
            if ":" not in keyval:
                continue
            k, _, v = keyval.partition(":")
            k = k.strip()
            v = v.strip()
            while stack and indent <= stack[-1][0]:
                stack.pop()
            cur = stack[-1][1] if stack else data
            if v == "":
                cur[k] = {}
                stack.append((indent, cur[k]))
            else:
                if v.lower() in ("true", "false"):
                    cur[k] = v.lower() == "true"
                else:
                    try:
                        cur[k] = int(v)
                    except Exception:
                        try:
                            cur[k] = float(v)
                        except Exception:
                            cur[k] = v.strip('"').strip("'")
        return data


def main():
    repo_root = Path(__file__).resolve().parent  # PEG2LNB
    cfg_path = repo_root / "configs" / "phase1.yaml"
    cfg = _load_yaml_min(cfg_path)

    work_dir = repo_root / cfg["work_dir"]
    lnb = cfg["lnb_build"]
    peg = cfg["peg"]
    vacuum_run_dir = repo_root / peg["vacuum_run_dir"]
    vacuum_run_dir_rel = os.path.relpath(vacuum_run_dir, start=repo_root)

    work_dir.mkdir(parents=True, exist_ok=True)
    system_gro = work_dir / "system.gro"
    system_top = work_dir / "system.top"

    # 1) build LNB (with solvent+ions, for later stripping)
    # lnb_gener_martini3.py 参数与注释中的一行命令一致
    cmd = [
        sys.executable,
        str(repo_root / "lnb_gener_martini3.py"),
        "-d",
        str(lnb["distance"]),
        "-r",
        str(lnb["radius"]),
        "-x",
        str(lnb["box"]),
        "-y",
        str(lnb["box"]),
        "-z",
        str(lnb["box"]),
        "-sol",
        str(lnb["solvent"]),
        "-salt",
        str(lnb["salt"]),
        "-a",
        str(lnb["area_per_lipid"]),
        "-gas",
        str(lnb["gas"]),
        "-gas_num",
        str(lnb["gas_num"]),
        "-o",
        str(system_gro),
        "-p",
        str(system_top),
    ]
    for name, count in lnb["lipids"].items():
        cmd.extend(["-u", f"{name}:{count}"])

    print("\n[Phase1] Building LNB with lnb_gener_martini3.py ...")
    subprocess.run(cmd, check=True, cwd=str(repo_root))

    # 2) grow PEG + remove all solvent/ions using version3/pipe.py
    # pipe.py 的配置需要 input_gro/output_gro/output_top，并带 dppe_to_peg/head_resname 等
    tmp_pipe_cfg = repo_root / "work" / "phase1_pipe_cfg.yaml"
    tmp_pipe_cfg.parent.mkdir(parents=True, exist_ok=True)

    # 用绝对路径，避免扁平化后相对路径失效
    pipe_cfg_text = f"""# auto-generated by run_phase1_pipeline.py
run_dir: "{vacuum_run_dir_rel}"
input_gro: "{str(system_gro.resolve())}"
output_gro: "{peg['output_gro']}"
output_top: "{peg['output_top']}"

radius: 10
box: 30

dppe_to_peg: "{peg['dppe_to_peg']}"
head_resname: "{peg['head_resname']}"
peg_bond_length_nm: {peg['peg_bond_length_nm']}
sphere_center: "{peg['sphere_center']}"

peg_resname: "{peg['peg_resname']}"
peg_length: {peg['peg_length']}
fix_overlap_enable: {str(peg.get('fix_overlap_enable', True)).lower()}

dpeg_itp: "" 
"""
    tmp_pipe_cfg.write_text(pipe_cfg_text, encoding="utf-8")

    print("\n[Phase1] Growing PEG + stripping solvent/ions (version3/pipe.py) ...")
    subprocess.run(
        [sys.executable, str(repo_root / "pipe.py"), str(tmp_pipe_cfg)],
        check=True,
        cwd=str(repo_root),
    )

    # 3) 不自动跑 MD：将目录拷到服务器后，在运行目录内自行执行 pipe.sh
    pipe_sh = vacuum_run_dir / "pipe.sh"
    if pipe_sh.is_file():
        try:
            pipe_sh.chmod(pipe_sh.stat().st_mode | 0o111)
        except OSError:
            pass
        print(
            "\n[Phase1] 结构已就绪，未自动运行模拟。请在服务器上进入运行目录后执行：\n"
            f"  cd \"{vacuum_run_dir}\"\n"
            "  chmod +x pipe.sh   # 若仍 Permission denied\n"
            "  ./pipe.sh\n"
            "  # 或: bash pipe.sh"
        )
    else:
        print(f"\n[Phase1] 警告: 未找到 {pipe_sh}，请检查 pipe.py 是否已复制 default 资源。")

    print("\n[Phase1] Done.")


if __name__ == "__main__":
    main()

