#!/bin/csh
#
# Generated by LNB-MDT

# Minimization
gmx_mpi grompp -f mdps/minimization_1.mdp -o minimization_1.tpr -c system.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm minimization_1
gmx_mpi grompp -f mdps/minimization_2.mdp -o minimization_2.tpr -c minimization_1.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm minimization_2


# Equilibration
gmx_mpi grompp -f mdps/equilibration_1.mdp -o equilibration_1.tpr -c minimization_2.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm equilibration_1

gmx_mpi grompp -f mdps/equilibration_2.mdp -o equilibration_2.tpr -c equilibration_1.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm equilibration_2

gmx_mpi grompp -f mdps/equilibration_3.mdp -o equilibration_3.tpr -c equilibration_2.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm equilibration_3

gmx_mpi grompp -f mdps/equilibration_4.mdp -o equilibration_4.tpr -c equilibration_3.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm equilibration_4

gmx_mpi grompp -f mdps/equilibration_5.mdp -o equilibration_5.tpr -c equilibration_4.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm equilibration_5

# Production
gmx_mpi grompp -f mdps/production.mdp -o production.tpr -c equilibration_5.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx_mpi mdrun -deffnm production

