#!/bin/csh
#
# Generated by LNB-MDT

# Final overlap fix output
set START_GRO = system_fix.gro
if ( ! -f "$START_GRO" ) then
    set START_GRO = system.gro
endif

# Minimization
gmx grompp -f mdps/minimization_1.mdp -o minimization_1.tpr -c $START_GRO -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx mdrun  -v -deffnm minimization_1
gmx grompp -f mdps/minimization_2.mdp -o minimization_2.tpr -c minimization_1.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx mdrun  -v -deffnm minimization_2

# Equilibration
gmx grompp -f mdps/equilibration_1.mdp -o equilibration_1.tpr -c minimization_2.gro -p system.top -r system.gro -n system.ndx -maxwarn 1
gmx mdrun  -v -deffnm equilibration_1
